"""add table in candidatedetails

Revision ID: 11d62610da83
Revises: ae5c3af36067
Create Date: 2025-10-08 12:52:33.917577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11d62610da83'
down_revision: Union[str, Sequence[str], None] = 'ae5c3af36067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_details_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_details_id'], ['candidate_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_focuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_details_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_details_id'], ['candidate_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controversies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_details_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_details_id'], ['candidate_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('political_experiences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_details_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_details_id'], ['candidate_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positive_contributions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_details_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_details_id'], ['candidate_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('candidate_details', 'political_experience')
    op.drop_column('candidate_details', 'achievements')
    op.drop_column('candidate_details', 'campaign_focus')
    op.drop_column('candidate_details', 'positive_contributions')
    op.drop_column('candidate_details', 'controversies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_details', sa.Column('controversies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('candidate_details', sa.Column('positive_contributions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('candidate_details', sa.Column('campaign_focus', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('candidate_details', sa.Column('achievements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('candidate_details', sa.Column('political_experience', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('positive_contributions')
    op.drop_table('political_experiences')
    op.drop_table('controversies')
    op.drop_table('campaign_focuses')
    op.drop_table('achievements')
    # ### end Alembic commands ###
