"""Add image_url to candidate

Revision ID: 403c0f83e001
Revises: 11d62610da83
Create Date: 2025-10-08 17:07:04.881464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403c0f83e001'
down_revision: Union[str, Sequence[str], None] = '11d62610da83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('image', sa.LargeBinary(), nullable=True, comment='Store candidate image as bytes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'image')
    # ### end Alembic commands ###
