"""Add image_ to candidate

Revision ID: a4bef384f82b
Revises: 403c0f83e001
Create Date: 2025-10-08 18:10:11.293486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4bef384f82b'
down_revision: Union[str, Sequence[str], None] = '403c0f83e001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'image',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=500),
               comment='Store MinIO image URL',
               existing_comment='Store candidate image as bytes',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'image',
               existing_type=sa.String(length=500),
               type_=postgresql.BYTEA(),
               comment='Store candidate image as bytes',
               existing_comment='Store MinIO image URL',
               existing_nullable=True)
    # ### end Alembic commands ###
