"""candidate_details

Revision ID: d5272fe13e84
Revises: 4b68ded179e6
Create Date: 2025-10-08 06:17:21.514013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5272fe13e84'
down_revision: Union[str, Sequence[str], None] = '4b68ded179e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_details',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('political_experience', sa.JSON(), nullable=True),
    sa.Column('campaign_focus', sa.JSON(), nullable=True),
    sa.Column('positive_contributions', sa.JSON(), nullable=True),
    sa.Column('controversies', sa.JSON(), nullable=True),
    sa.Column('past_elections', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_details_id'), 'candidate_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_details_id'), table_name='candidate_details')
    op.drop_table('candidate_details')
    # ### end Alembic commands ###
